name: Code Style

on:
  [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install black isort

      - name: Ensure code is blackified
        run: black . --check --diff

      - name: Ensure imports are sorted
        run: isort . --check --diff
